// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An API Configuration is a combination of settings for both the Managed
/// Service and Gateways serving this API Config.
public struct ApiConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the API Config.
  /// Format: projects/{project}/locations/global/apis/{api}/configs/{api_config}
  public var name: Swift.String = Swift.String()

  /// Output only. Created time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Updated time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Immutable. The Google Cloud IAM Service Account that Gateways serving this config
  /// should use to authenticate to other services. This may either be the
  /// Service Account's email
  /// (`{ACCOUNT_ID}@{PROJECT}.iam.gserviceaccount.com`) or its full resource
  /// name (`projects/{PROJECT}/accounts/{UNIQUE_ID}`). This is most often used
  /// when the service is a GCP resource such as a Cloud Run Service or an
  /// IAP-secured service.
  public var gatewayServiceAccount: Swift.String = Swift.String()

  /// Output only. The ID of the associated Service Config (
  /// https://cloud.google.com/service-infrastructure/docs/glossary#config).
  public var serviceConfigId: Swift.String = Swift.String()

  /// Output only. State of the API Config.
  public var state: ApiConfig.State = ApiConfig.State()

  /// Optional. OpenAPI specification documents. If specified, grpc_services and
  /// managed_service_configs must not be included.
  public var openapiDocuments: [ApiConfig.OpenApiDocument] = []

  /// Optional. gRPC service definition files. If specified, openapi_documents must
  /// not be included.
  public var grpcServices: [ApiConfig.GrpcServiceDefinition] = []

  /// Optional. Service Configuration files. At least one must be included when using gRPC
  /// service definitions. See
  /// https://cloud.google.com/endpoints/docs/grpc/grpc-service-config#service_configuration_overview
  /// for the expected file contents.
  ///
  /// If multiple files are specified, the files are merged with the following
  /// rules:
  /// * All singular scalar fields are merged using "last one wins" semantics in
  /// the order of the files uploaded.
  /// * Repeated fields are concatenated.
  /// * Singular embedded messages are merged using these rules for nested
  /// fields.
  public var managedServiceConfigs: [ApiConfig.File] = []

  /// Initialize a new instance of `ApiConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApiConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A lightweight description of a file.
  public struct File: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The file path (full or relative path). This is typically the path of the
    /// file when it is uploaded.
    public var path: Swift.String = Swift.String()

    /// The bytes that constitute the file.
    public var contents: Foundation.Data = Foundation.Data()

    /// Initialize a new instance of `File`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = File().with { $0.path = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apigateway.v1.ApiConfig.File"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// An OpenAPI Specification Document describing an API.
  public struct OpenApiDocument: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The OpenAPI Specification document file.
    public var document: ApiConfig.File? = nil

    /// Initialize a new instance of `OpenApiDocument`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OpenApiDocument().with { $0.document = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apigateway.v1.ApiConfig.OpenApiDocument"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A gRPC service definition.
  public struct GrpcServiceDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Input only. File descriptor set, generated by protoc.
    ///
    /// To generate, use protoc with imports and source info included.
    /// For an example test.proto file, the following command would put the value
    /// in a new file named out.pb.
    ///
    /// $ protoc --include_imports --include_source_info test.proto -o out.pb
    public var fileDescriptorSet: ApiConfig.File? = nil

    /// Optional. Uncompiled proto files associated with the descriptor set, used for
    /// display purposes (server-side compilation is not supported). These
    /// should match the inputs to 'protoc' command used to generate
    /// file_descriptor_set.
    public var source: [ApiConfig.File] = []

    /// Initialize a new instance of `GrpcServiceDefinition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GrpcServiceDefinition().with { $0.fileDescriptorSet = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apigateway.v1.ApiConfig.GrpcServiceDefinition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// All the possible API Config states.
  public enum State: Codable, Equatable, Sendable {
    /// API Config does not have a state yet.
    case unspecified
    /// API Config is being created and deployed to the API Controller.
    case creating
    /// API Config is ready for use by Gateways.
    case active
    /// API Config creation failed.
    case failed
    /// API Config is being deleted.
    case deleting
    /// API Config is being updated.
    case updating
    /// API Config settings are being activated in downstream systems.
    /// API Configs in this state cannot be used by Gateways.
    case activating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .failed: return 3
      case .deleting: return 4
      case .updating: return 5
      case .activating: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .updating: return "UPDATING"
      case .activating: return "ACTIVATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      case "UPDATING": self = .updating
      case "ACTIVATING": self = .activating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .failed
      case 4: self = .deleting
      case 5: self = .updating
      case 6: self = .activating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .activating: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apigateway.v1.ApiConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
