// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ApiGatewayServiceRetry: ApiGatewayServiceStub {
    let inner: any ApiGatewayServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any ApiGatewayServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listGateways(
      request: ListGatewaysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ListGatewaysResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGatewaysRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiGatewayV1.ListGatewaysResponse
          in
          return try await self.inner.listGateways(request: r, options: o)
        })
    }

    public func getGateway(
      request: GetGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.Gateway {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGatewayRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiGatewayV1.Gateway
          in
          return try await self.inner.getGateway(request: r, options: o)
        })
    }

    public func createGateway(
      request: CreateGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGatewayRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGateway(request: r, options: o)
        })
    }

    public func updateGateway(
      request: UpdateGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateGatewayRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGateway(request: r, options: o)
        })
    }

    public func deleteGateway(
      request: DeleteGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGatewayRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGateway(request: r, options: o)
        })
    }

    public func listApis(
      request: ListApisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ListApisResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListApisRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiGatewayV1.ListApisResponse
          in
          return try await self.inner.listApis(request: r, options: o)
        })
    }

    public func getApi(
      request: GetApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.Api {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetApiRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiGatewayV1.Api
          in
          return try await self.inner.getApi(request: r, options: o)
        })
    }

    public func createApi(
      request: CreateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateApiRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createApi(request: r, options: o)
        })
    }

    public func updateApi(
      request: UpdateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateApiRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateApi(request: r, options: o)
        })
    }

    public func deleteApi(
      request: DeleteApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteApiRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteApi(request: r, options: o)
        })
    }

    public func listApiConfigs(
      request: ListApiConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ListApiConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListApiConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiGatewayV1.ListApiConfigsResponse
          in
          return try await self.inner.listApiConfigs(request: r, options: o)
        })
    }

    public func getApiConfig(
      request: GetApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ApiConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetApiConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiGatewayV1.ApiConfig
          in
          return try await self.inner.getApiConfig(request: r, options: o)
        })
    }

    public func createApiConfig(
      request: CreateApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateApiConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createApiConfig(request: r, options: o)
        })
    }

    public func updateApiConfig(
      request: UpdateApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateApiConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateApiConfig(request: r, options: o)
        })
    }

    public func deleteApiConfig(
      request: DeleteApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteApiConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteApiConfig(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
