// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

/// The API Gateway Service is the interface for managing API Gateways.
///
/// @Snippet(path: "ApiGatewayServiceQuickstart")
public class ApiGatewayServiceClient: Clients.ApiGatewayServiceProtocol {
  let inner: any Clients.ApiGatewayServiceStub

  /// Creates a new `ApiGatewayServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiGatewayServiceStub = try Clients.ApiGatewayServiceTransport(options)
    inner = Clients.ApiGatewayServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiGatewayServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists Gateways in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListGateways")
  public func listGateways(
    request: ListGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ListGatewaysResponse {
    try await self.inner.listGateways(request: request, options: options)
  }

  /// Lists Gateways in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListGateways")
  public func listGateways(
    byItem: ListGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Gateway, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApigatewayV1.ListGatewaysResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGateways(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_GetGateway")
  public func getGateway(
    request: GetGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.Gateway {
    try await self.inner.getGateway(request: request, options: options)
  }

  /// Creates a new Gateway in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateGateway")
  public func createGateway(
    request: CreateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createGateway(request: request, options: options)
  }

  /// Creates a new Gateway in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateGateway")
  public func createGateway(
    withPolling: CreateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Gateway> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Gateway>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Gateway(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createGateway(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Gateway>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateGateway")
  public func updateGateway(
    request: UpdateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateGateway(request: request, options: options)
  }

  /// Updates the parameters of a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateGateway")
  public func updateGateway(
    withPolling: UpdateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Gateway> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Gateway>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Gateway(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateGateway(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Gateway>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteGateway")
  public func deleteGateway(
    request: DeleteGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteGateway(request: request, options: options)
  }

  /// Deletes a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteGateway")
  public func deleteGateway(
    withPolling: DeleteGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteGateway(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists Apis in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApis")
  public func listApis(
    request: ListApisRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ListApisResponse {
    try await self.inner.listApis(request: request, options: options)
  }

  /// Lists Apis in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApis")
  public func listApis(
    byItem: ListApisRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Api, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApigatewayV1.ListApisResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listApis(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_GetApi")
  public func getApi(
    request: GetApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.Api {
    try await self.inner.getApi(request: request, options: options)
  }

  /// Creates a new Api in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApi")
  public func createApi(
    request: CreateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createApi(request: request, options: options)
  }

  /// Creates a new Api in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApi")
  public func createApi(
    withPolling: CreateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Api> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Api>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Api(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createApi(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Api>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApi")
  public func updateApi(
    request: UpdateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateApi(request: request, options: options)
  }

  /// Updates the parameters of a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApi")
  public func updateApi(
    withPolling: UpdateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Api> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Api>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Api(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateApi(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Api>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApi")
  public func deleteApi(
    request: DeleteApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteApi(request: request, options: options)
  }

  /// Deletes a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApi")
  public func deleteApi(
    withPolling: DeleteApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteApi(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists ApiConfigs in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApiConfigs")
  public func listApiConfigs(
    request: ListApiConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ListApiConfigsResponse {
    try await self.inner.listApiConfigs(request: request, options: options)
  }

  /// Lists ApiConfigs in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApiConfigs")
  public func listApiConfigs(
    byItem: ListApiConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ApiConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApigatewayV1.ListApiConfigsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listApiConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_GetApiConfig")
  public func getApiConfig(
    request: GetApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ApiConfig {
    try await self.inner.getApiConfig(request: request, options: options)
  }

  /// Creates a new ApiConfig in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApiConfig")
  public func createApiConfig(
    request: CreateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createApiConfig(request: request, options: options)
  }

  /// Creates a new ApiConfig in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApiConfig")
  public func createApiConfig(
    withPolling: CreateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ApiConfig>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try ApiConfig(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createApiConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ApiConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApiConfig")
  public func updateApiConfig(
    request: UpdateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateApiConfig(request: request, options: options)
  }

  /// Updates the parameters of a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApiConfig")
  public func updateApiConfig(
    withPolling: UpdateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ApiConfig>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try ApiConfig(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateApiConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ApiConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApiConfig")
  public func deleteApiConfig(
    request: DeleteApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteApiConfig(request: request, options: options)
  }

  /// Deletes a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApiConfig")
  public func deleteApiConfig(
    withPolling: DeleteApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteApiConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ApiGatewayService_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ApiGatewayService_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ApiGatewayService_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ApiGatewayService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiGatewayServiceClient`.
  ///
  /// To mock `ApiGatewayServiceClient` change your functions to receive
  /// `some ApiGatewayServiceProtocol` or `any ApiGatewayServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiGatewayServiceProtocol {
    /// See `ApiGatewayServiceClient.listGateways`.
    func listGateways(request: ListGatewaysRequest) async throws
      -> GoogleCloudApigatewayV1.ListGatewaysResponse

    /// See `ApiGatewayServiceClient.listGateways`.
    func listGateways(
      byItem: ListGatewaysRequest
    ) throws -> any AsyncSequence<Gateway, Swift.Error>

    /// See `ApiGatewayServiceClient.listGateways`.
    func listGateways(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Gateway, Swift.Error>

    /// See `ApiGatewayServiceClient.getGateway`.
    func getGateway(request: GetGatewayRequest) async throws -> GoogleCloudApigatewayV1.Gateway

    /// See `ApiGatewayServiceClient.getGateway`.
    func getGateway(
      name: Swift.String,
    ) async throws -> GoogleCloudApigatewayV1.Gateway

    /// See `ApiGatewayServiceClient.createGateway`.
    func createGateway(request: CreateGatewayRequest) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.createGateway`.
    func createGateway(withPolling: CreateGatewayRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Gateway>

    /// See `ApiGatewayServiceClient.createGateway`.
    func createGateway(
      parent: Swift.String,
      gateway: Gateway?,
      gatewayId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Gateway>

    /// See `ApiGatewayServiceClient.updateGateway`.
    func updateGateway(request: UpdateGatewayRequest) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.updateGateway`.
    func updateGateway(withPolling: UpdateGatewayRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Gateway>

    /// See `ApiGatewayServiceClient.updateGateway`.
    func updateGateway(
      gateway: Gateway?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Gateway>

    /// See `ApiGatewayServiceClient.deleteGateway`.
    func deleteGateway(request: DeleteGatewayRequest) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.deleteGateway`.
    func deleteGateway(withPolling: DeleteGatewayRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `ApiGatewayServiceClient.deleteGateway`.
    func deleteGateway(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ApiGatewayServiceClient.listApis`.
    func listApis(request: ListApisRequest) async throws -> GoogleCloudApigatewayV1.ListApisResponse

    /// See `ApiGatewayServiceClient.listApis`.
    func listApis(
      byItem: ListApisRequest
    ) throws -> any AsyncSequence<Api, Swift.Error>

    /// See `ApiGatewayServiceClient.listApis`.
    func listApis(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Api, Swift.Error>

    /// See `ApiGatewayServiceClient.getApi`.
    func getApi(request: GetApiRequest) async throws -> GoogleCloudApigatewayV1.Api

    /// See `ApiGatewayServiceClient.getApi`.
    func getApi(
      name: Swift.String,
    ) async throws -> GoogleCloudApigatewayV1.Api

    /// See `ApiGatewayServiceClient.createApi`.
    func createApi(request: CreateApiRequest) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.createApi`.
    func createApi(withPolling: CreateApiRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Api>

    /// See `ApiGatewayServiceClient.createApi`.
    func createApi(
      parent: Swift.String,
      api: Api?,
      apiId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Api>

    /// See `ApiGatewayServiceClient.updateApi`.
    func updateApi(request: UpdateApiRequest) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.updateApi`.
    func updateApi(withPolling: UpdateApiRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Api>

    /// See `ApiGatewayServiceClient.updateApi`.
    func updateApi(
      api: Api?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Api>

    /// See `ApiGatewayServiceClient.deleteApi`.
    func deleteApi(request: DeleteApiRequest) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.deleteApi`.
    func deleteApi(withPolling: DeleteApiRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `ApiGatewayServiceClient.deleteApi`.
    func deleteApi(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ApiGatewayServiceClient.listApiConfigs`.
    func listApiConfigs(request: ListApiConfigsRequest) async throws
      -> GoogleCloudApigatewayV1.ListApiConfigsResponse

    /// See `ApiGatewayServiceClient.listApiConfigs`.
    func listApiConfigs(
      byItem: ListApiConfigsRequest
    ) throws -> any AsyncSequence<ApiConfig, Swift.Error>

    /// See `ApiGatewayServiceClient.listApiConfigs`.
    func listApiConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ApiConfig, Swift.Error>

    /// See `ApiGatewayServiceClient.getApiConfig`.
    func getApiConfig(request: GetApiConfigRequest) async throws
      -> GoogleCloudApigatewayV1.ApiConfig

    /// See `ApiGatewayServiceClient.getApiConfig`.
    func getApiConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudApigatewayV1.ApiConfig

    /// See `ApiGatewayServiceClient.createApiConfig`.
    func createApiConfig(request: CreateApiConfigRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.createApiConfig`.
    func createApiConfig(withPolling: CreateApiConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<ApiConfig>

    /// See `ApiGatewayServiceClient.createApiConfig`.
    func createApiConfig(
      parent: Swift.String,
      apiConfig: ApiConfig?,
      apiConfigId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig>

    /// See `ApiGatewayServiceClient.updateApiConfig`.
    func updateApiConfig(request: UpdateApiConfigRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.updateApiConfig`.
    func updateApiConfig(withPolling: UpdateApiConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<ApiConfig>

    /// See `ApiGatewayServiceClient.updateApiConfig`.
    func updateApiConfig(
      apiConfig: ApiConfig?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig>

    /// See `ApiGatewayServiceClient.deleteApiConfig`.
    func deleteApiConfig(request: DeleteApiConfigRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.deleteApiConfig`.
    func deleteApiConfig(withPolling: DeleteApiConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `ApiGatewayServiceClient.deleteApiConfig`.
    func deleteApiConfig(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ApiGatewayServiceClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `ApiGatewayServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `ApiGatewayServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `ApiGatewayServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws

    /// See `ApiGatewayServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `ApiGatewayServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

    /// See `ApiGatewayServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `ApiGatewayServiceClient.listGateways`.
    func listGateways(
      request: ListGatewaysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApigatewayV1.ListGatewaysResponse

    /// See `ApiGatewayServiceClient.listGateways`.
    func listGateways(
      byItem: ListGatewaysRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Gateway, Swift.Error>

    /// See `ApiGatewayServiceClient.getGateway`.
    func getGateway(
      request: GetGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApigatewayV1.Gateway

    /// See `ApiGatewayServiceClient.createGateway`.
    func createGateway(
      request: CreateGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.createGateway`.
    func createGateway(
      withPolling: CreateGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Gateway>

    /// See `ApiGatewayServiceClient.updateGateway`.
    func updateGateway(
      request: UpdateGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.updateGateway`.
    func updateGateway(
      withPolling: UpdateGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Gateway>

    /// See `ApiGatewayServiceClient.deleteGateway`.
    func deleteGateway(
      request: DeleteGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.deleteGateway`.
    func deleteGateway(
      withPolling: DeleteGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ApiGatewayServiceClient.listApis`.
    func listApis(
      request: ListApisRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApigatewayV1.ListApisResponse

    /// See `ApiGatewayServiceClient.listApis`.
    func listApis(
      byItem: ListApisRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Api, Swift.Error>

    /// See `ApiGatewayServiceClient.getApi`.
    func getApi(
      request: GetApiRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApigatewayV1.Api

    /// See `ApiGatewayServiceClient.createApi`.
    func createApi(
      request: CreateApiRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.createApi`.
    func createApi(
      withPolling: CreateApiRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Api>

    /// See `ApiGatewayServiceClient.updateApi`.
    func updateApi(
      request: UpdateApiRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.updateApi`.
    func updateApi(
      withPolling: UpdateApiRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Api>

    /// See `ApiGatewayServiceClient.deleteApi`.
    func deleteApi(
      request: DeleteApiRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.deleteApi`.
    func deleteApi(
      withPolling: DeleteApiRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ApiGatewayServiceClient.listApiConfigs`.
    func listApiConfigs(
      request: ListApiConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApigatewayV1.ListApiConfigsResponse

    /// See `ApiGatewayServiceClient.listApiConfigs`.
    func listApiConfigs(
      byItem: ListApiConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ApiConfig, Swift.Error>

    /// See `ApiGatewayServiceClient.getApiConfig`.
    func getApiConfig(
      request: GetApiConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudApigatewayV1.ApiConfig

    /// See `ApiGatewayServiceClient.createApiConfig`.
    func createApiConfig(
      request: CreateApiConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.createApiConfig`.
    func createApiConfig(
      withPolling: CreateApiConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig>

    /// See `ApiGatewayServiceClient.updateApiConfig`.
    func updateApiConfig(
      request: UpdateApiConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.updateApiConfig`.
    func updateApiConfig(
      withPolling: UpdateApiConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig>

    /// See `ApiGatewayServiceClient.deleteApiConfig`.
    func deleteApiConfig(
      request: DeleteApiConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `ApiGatewayServiceClient.deleteApiConfig`.
    func deleteApiConfig(
      withPolling: DeleteApiConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ApiGatewayServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `ApiGatewayServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `ApiGatewayServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ApiGatewayServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ApiGatewayServiceProtocol {
  public func listGateways(request: ListGatewaysRequest) async throws
    -> GoogleCloudApigatewayV1.ListGatewaysResponse
  {
    try await self.listGateways(request: request, options: .init())
  }

  public func listGateways(
    request: ListGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ListGatewaysResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listGateways(
    byItem: ListGatewaysRequest
  ) throws -> any AsyncSequence<Gateway, Swift.Error> {
    try self.listGateways(byItem: byItem, options: .init())
  }

  public func listGateways(
    byItem: ListGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Gateway, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApigatewayV1.ListGatewaysResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGateways(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Gateway, Swift.Error> {
    let request = ListGatewaysRequest().with {
      $0.parent = parent
    }
    return try self.listGateways(byItem: request)
  }

  public func getGateway(request: GetGatewayRequest) async throws -> GoogleCloudApigatewayV1.Gateway
  {
    try await self.getGateway(request: request, options: .init())
  }

  public func getGateway(
    request: GetGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.Gateway {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getGateway(
    name: Swift.String,
  ) async throws -> GoogleCloudApigatewayV1.Gateway {
    let request = GetGatewayRequest().with {
      $0.name = name
    }
    return try await self.getGateway(request: request)
  }

  public func createGateway(request: CreateGatewayRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createGateway(request: request, options: .init())
  }

  public func createGateway(
    request: CreateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createGateway(withPolling: CreateGatewayRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Gateway>
  {
    try await self.createGateway(withPolling: withPolling, options: .init())
  }

  public func createGateway(
    withPolling: CreateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Gateway> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Gateway>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createGateway(
    parent: Swift.String,
    gateway: Gateway?,
    gatewayId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Gateway> {
    let request = CreateGatewayRequest().with {
      $0.parent = parent
      $0.gateway = gateway
      $0.gatewayId = gatewayId
    }
    return try await self.createGateway(withPolling: request)
  }

  public func updateGateway(request: UpdateGatewayRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateGateway(request: request, options: .init())
  }

  public func updateGateway(
    request: UpdateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateGateway(withPolling: UpdateGatewayRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Gateway>
  {
    try await self.updateGateway(withPolling: withPolling, options: .init())
  }

  public func updateGateway(
    withPolling: UpdateGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Gateway> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Gateway>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateGateway(
    gateway: Gateway?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Gateway> {
    let request = UpdateGatewayRequest().with {
      $0.gateway = gateway
      $0.updateMask = updateMask
    }
    return try await self.updateGateway(withPolling: request)
  }

  public func deleteGateway(request: DeleteGatewayRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteGateway(request: request, options: .init())
  }

  public func deleteGateway(
    request: DeleteGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteGateway(withPolling: DeleteGatewayRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteGateway(withPolling: withPolling, options: .init())
  }

  public func deleteGateway(
    withPolling: DeleteGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteGateway(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteGatewayRequest().with {
      $0.name = name
    }
    return try await self.deleteGateway(withPolling: request)
  }

  public func listApis(request: ListApisRequest) async throws
    -> GoogleCloudApigatewayV1.ListApisResponse
  {
    try await self.listApis(request: request, options: .init())
  }

  public func listApis(
    request: ListApisRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ListApisResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listApis(
    byItem: ListApisRequest
  ) throws -> any AsyncSequence<Api, Swift.Error> {
    try self.listApis(byItem: byItem, options: .init())
  }

  public func listApis(
    byItem: ListApisRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Api, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApigatewayV1.ListApisResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listApis(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Api, Swift.Error> {
    let request = ListApisRequest().with {
      $0.parent = parent
    }
    return try self.listApis(byItem: request)
  }

  public func getApi(request: GetApiRequest) async throws -> GoogleCloudApigatewayV1.Api {
    try await self.getApi(request: request, options: .init())
  }

  public func getApi(
    request: GetApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.Api {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getApi(
    name: Swift.String,
  ) async throws -> GoogleCloudApigatewayV1.Api {
    let request = GetApiRequest().with {
      $0.name = name
    }
    return try await self.getApi(request: request)
  }

  public func createApi(request: CreateApiRequest) async throws -> GoogleLongrunning.Operation {
    try await self.createApi(request: request, options: .init())
  }

  public func createApi(
    request: CreateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createApi(withPolling: CreateApiRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Api>
  {
    try await self.createApi(withPolling: withPolling, options: .init())
  }

  public func createApi(
    withPolling: CreateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Api> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Api>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createApi(
    parent: Swift.String,
    api: Api?,
    apiId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Api> {
    let request = CreateApiRequest().with {
      $0.parent = parent
      $0.api = api
      $0.apiId = apiId
    }
    return try await self.createApi(withPolling: request)
  }

  public func updateApi(request: UpdateApiRequest) async throws -> GoogleLongrunning.Operation {
    try await self.updateApi(request: request, options: .init())
  }

  public func updateApi(
    request: UpdateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateApi(withPolling: UpdateApiRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Api>
  {
    try await self.updateApi(withPolling: withPolling, options: .init())
  }

  public func updateApi(
    withPolling: UpdateApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Api> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Api>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateApi(
    api: Api?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Api> {
    let request = UpdateApiRequest().with {
      $0.api = api
      $0.updateMask = updateMask
    }
    return try await self.updateApi(withPolling: request)
  }

  public func deleteApi(request: DeleteApiRequest) async throws -> GoogleLongrunning.Operation {
    try await self.deleteApi(request: request, options: .init())
  }

  public func deleteApi(
    request: DeleteApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteApi(withPolling: DeleteApiRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteApi(withPolling: withPolling, options: .init())
  }

  public func deleteApi(
    withPolling: DeleteApiRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteApi(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteApiRequest().with {
      $0.name = name
    }
    return try await self.deleteApi(withPolling: request)
  }

  public func listApiConfigs(request: ListApiConfigsRequest) async throws
    -> GoogleCloudApigatewayV1.ListApiConfigsResponse
  {
    try await self.listApiConfigs(request: request, options: .init())
  }

  public func listApiConfigs(
    request: ListApiConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ListApiConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listApiConfigs(
    byItem: ListApiConfigsRequest
  ) throws -> any AsyncSequence<ApiConfig, Swift.Error> {
    try self.listApiConfigs(byItem: byItem, options: .init())
  }

  public func listApiConfigs(
    byItem: ListApiConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ApiConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApigatewayV1.ListApiConfigsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listApiConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ApiConfig, Swift.Error> {
    let request = ListApiConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listApiConfigs(byItem: request)
  }

  public func getApiConfig(request: GetApiConfigRequest) async throws
    -> GoogleCloudApigatewayV1.ApiConfig
  {
    try await self.getApiConfig(request: request, options: .init())
  }

  public func getApiConfig(
    request: GetApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudApigatewayV1.ApiConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getApiConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudApigatewayV1.ApiConfig {
    let request = GetApiConfigRequest().with {
      $0.name = name
    }
    return try await self.getApiConfig(request: request)
  }

  public func createApiConfig(request: CreateApiConfigRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createApiConfig(request: request, options: .init())
  }

  public func createApiConfig(
    request: CreateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createApiConfig(withPolling: CreateApiConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ApiConfig>
  {
    try await self.createApiConfig(withPolling: withPolling, options: .init())
  }

  public func createApiConfig(
    withPolling: CreateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ApiConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createApiConfig(
    parent: Swift.String,
    apiConfig: ApiConfig?,
    apiConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig> {
    let request = CreateApiConfigRequest().with {
      $0.parent = parent
      $0.apiConfig = apiConfig
      $0.apiConfigId = apiConfigId
    }
    return try await self.createApiConfig(withPolling: request)
  }

  public func updateApiConfig(request: UpdateApiConfigRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateApiConfig(request: request, options: .init())
  }

  public func updateApiConfig(
    request: UpdateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateApiConfig(withPolling: UpdateApiConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ApiConfig>
  {
    try await self.updateApiConfig(withPolling: withPolling, options: .init())
  }

  public func updateApiConfig(
    withPolling: UpdateApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ApiConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateApiConfig(
    apiConfig: ApiConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<ApiConfig> {
    let request = UpdateApiConfigRequest().with {
      $0.apiConfig = apiConfig
      $0.updateMask = updateMask
    }
    return try await self.updateApiConfig(withPolling: request)
  }

  public func deleteApiConfig(request: DeleteApiConfigRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteApiConfig(request: request, options: .init())
  }

  public func deleteApiConfig(
    request: DeleteApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteApiConfig(withPolling: DeleteApiConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteApiConfig(withPolling: withPolling, options: .init())
  }

  public func deleteApiConfig(
    withPolling: DeleteApiConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteApiConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteApiConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteApiConfig(withPolling: request)
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
